name: Build and Deploy
on: [ push ]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: vuepress-deploy
        uses: jenkey2011/vuepress-deploy@master
        env:
          ACCESS_TOKEN: ${{ secrets.ITMO_DB_VUEPRESS }}
          TARGET_REPO: lipa44/itmo-db-course
          BUILD_SCRIPT: cd docs && yarn install && yarn build
          BUILD_DIR: src/.vuepress/dist
